Autoimports on unresolved references
AlexanderPrendota/kotlin-compiler-server pull request #185
Opened 2020-08-14 14:03 UTC by PolinB

2020-08-24 16:51 UTC, AlexanderPrendota requested changes

2020-08-24 16:51 UTC, AlexanderPrendota commented on src/main/kotlin/com/compiler/server/compiler/components/ErrorAnalyzer.kt
> +    withImports: Boolean = false
when we don't need the imports?

2020-08-24 16:51 UTC, AlexanderPrendota commented on src/main/kotlin/com/compiler/server/compiler/components/ErrorAnalyzer.kt
> +  private fun completionsForErrorErrorMessage(message: String, withImports: Boolean): List<Completion>? {
`ErrorError`

2020-08-24 16:51 UTC, AlexanderPrendota commented on src/main/kotlin/com/compiler/server/compiler/components/IndexationProvider.kt
> +  @Value("\${indexes.file}") private val indexesFileName: String = ""
in constructor

2020-08-24 16:51 UTC, AlexanderPrendota commented on src/main/kotlin/com/compiler/server/compiler/components/IndexationProvider.kt
> +    println("INIT")
remove

2020-08-24 16:51 UTC, AlexanderPrendota commented on src/main/kotlin/com/compiler/server/controllers/CompilerRestController.kt
> +  fun highlightEndpoint(@RequestBody project: Project) = kotlinProjectExecutor.highlight(project)
return type

2020-08-25 07:51 UTC, PolinB commented on src/main/kotlin/com/compiler/server/compiler/components/ErrorAnalyzer.kt
> +    withImports: Boolean = false
1. In translate(files: List<KtFile>, arguments: List<String>, coreEnvironment: KotlinCoreEnvironment)
2. In completion when we check that prefix unresolved or not. We don't want imports for all unresolved references.

2020-08-25 08:22 UTC, AlexanderPrendota approved these changes

2020-08-25 08:23 UTC, AlexanderPrendota requested changes

2020-08-25 08:23 UTC, AlexanderPrendota commented on src/main/kotlin/com/compiler/server/compiler/components/IndexationProvider.kt
> +  private val UNRESOLVED_REFERENCE_PREFIX = "Unresolved reference: "
I have already seen that constant in ErrorAnalyzer

2020-08-25 09:04 UTC, AlexanderPrendota approved these changes

2020-08-25 09:04 UTC, merged