Support imports for JS
AlexanderPrendota/kotlin-compiler-server pull request #228
Opened 2020-12-03 17:35 UTC by PolinB

2020-12-03 21:34 UTC, AlexanderPrendota requested changes

2020-12-03 21:34 UTC, AlexanderPrendota commented on indexation/build.gradle.kts
> +    implementation("org.jetbrains.intellij.deps:trove4j:1.0.20200330")
why do u need it here?

2020-12-03 21:34 UTC, AlexanderPrendota commented on indexation/src/main/kotlin/DescriptorsUtils.kt
> +          icon = "class"
you have constants for this. But maybe it should be an enum class

2020-12-03 21:34 UTC, AlexanderPrendota commented on indexation/src/main/kotlin/KotlinEnvironment.kt
> +class KotlinEnvironmentConfiguration(val librariesFile: LibrariesFile) {
maybe in a common module?

2020-12-03 21:34 UTC, AlexanderPrendota commented on src/main/kotlin/com/compiler/server/compiler/components/indexation/IndexationJsProvider.kt
> +class IndexationJsProvider(
it should be one component with two functions

2020-12-22 17:14 UTC, bashor commented on src/main/kotlin/com/compiler/server/compiler/components/IndexationProvider.kt
> +  @Value("\${indexesJs.file}") private val indexesJsFileName: String
JFTR: I think eventually we will need to add more platforms

2020-12-22 17:14 UTC, bashor commented on src/test/kotlin/com/compiler/server/ImportTest.kt
> +  fun `open bracket after import completion js`() {
Would be nice to add a test for some API available only on K/JS.

2020-12-22 17:14 UTC, bashor commented on src/test/kotlin/com/compiler/server/ImportTest.kt
> +  fun `open bracket after import completion js`() {
https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.js/

2021-02-01 12:24 UTC, PolinB commented on src/test/kotlin/com/compiler/server/ImportTest.kt
> +  fun `open bracket after import completion js`() {
I tried to do tests for JS, but I couldn't find a specific function without arguments that I need to import

2021-02-01 12:26 UTC, PolinB commented on indexation/src/main/kotlin/DescriptorsUtils.kt
> +    else -> null
I don't know what that means. Can you give me an example?

2021-02-01 12:27 UTC, PolinB commented on indexation/src/main/kotlin/KotlinEnvironment.kt
> +  init {
Can you give me an example, please? I don't understand how do it.

2021-02-02 12:14 UTC, bashor commented on indexation/src/main/kotlin/DescriptorsUtils.kt
> +    else -> null
PropertyDescriptor

2021-02-02 12:14 UTC, bashor commented on src/test/kotlin/com/compiler/server/ImportTest.kt
> +  fun `open bracket after import completion js`() {
Does the feature work only for functions?

2021-02-02 12:14 UTC, bashor commented on src/test/kotlin/com/compiler/server/ImportTest.kt
> +  fun `open bracket after import completion js`() {
You can try this one https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.js/json.html

2021-02-04 11:43 UTC, AlexanderPrendota commented on common/src/main/kotlin/component/KotlinEnvironment.kt
> +      "-Xuse-experimental=kotlin.experimental.ExperimentalTypeInference",
@bashor we can just remove all experimental flags over here?

2021-02-04 13:24 UTC, AlexanderPrendota commented on common/src/main/kotlin/component/KotlinEnvironment.kt
> +    configFiles = EnvironmentConfigFiles.JVM_CONFIG_FILES
is it important for the online version?

2021-02-04 13:24 UTC, AlexanderPrendota commented on common/src/main/kotlin/component/KotlinEnvironment.kt
> +    val arguments = K2JVMCompilerArguments()
is it important for the online version?

2021-02-04 13:26 UTC, AlexanderPrendota commented on indexation/src/main/kotlin/KotlinEnvironment.kt
> +class KotlinEnvironmentConfiguration(fileName: String) {
yes

2021-02-08 18:55 UTC, AlexanderPrendota commented
@PolinB tests =)

2021-02-10 07:33 UTC, AlexanderPrendota approved these changes

2021-02-10 07:40 UTC, merged