Rewrite jvm indexation with declaration descriptors
AlexanderPrendota/kotlin-compiler-server pull request #231
Opened 2020-12-06 20:02 UTC by PolinB

2020-12-07 17:45 UTC, AlexanderPrendota requested changes

2020-12-07 17:45 UTC, AlexanderPrendota commented on indexation/src/main/kotlin/DescriptorsUtils.kt
> +  return when (this) {
why do u need "when" here? only one condition

2020-12-07 17:45 UTC, AlexanderPrendota commented on indexation/src/main/kotlin/DescriptorsUtils.kt
> +  packages.forEach { fqName ->
val imports = packages.map{ ... }

2020-12-07 17:45 UTC, AlexanderPrendota commented on indexation/src/main/kotlin/JsIndexationBuilder.kt
> +        imports.addAll(moduleDescriptor.allImportsInfo())
vak imports = something.map { ... }, is it possible ?

2020-12-07 17:45 UTC, AlexanderPrendota commented on indexation/src/main/kotlin/JvmIndexationBuilder.kt
> +    File(outputFilename).writeText(jacksonObjectMapper().writerWithDefaultPrettyPrinter().writeValueAsString(getAllVariants()))
why do u need a pretty printer here?

2020-12-07 17:45 UTC, AlexanderPrendota commented on indexation/src/main/kotlin/JvmIndexationBuilder.kt
> +    val imports = mutableListOf<ImportInfo>()
when I see the construction `val some = mutableListOf<ImportInfo>()` I always think we can replace one => something.map {}

2020-12-10 17:43 UTC, AlexanderPrendota requested changes

2020-12-10 17:43 UTC, AlexanderPrendota commented on indexation/src/main/kotlin/JsIndexationBuilder.kt
> +      }.distinct()
Is it possible to avoid a distinct call?

2020-12-11 09:54 UTC, PolinB commented on indexation/src/main/kotlin/JsIndexationBuilder.kt
> +      }.distinct()
I believe that distinct call is needed, because without it, there are 100,000 more lines in the json file.

2020-12-11 10:04 UTC, merged