Add JS IR compiler support
AlexanderPrendota/kotlin-compiler-server pull request #269
Opened 2021-03-31 09:08 UTC by ilgonmic

Initial support of JS IR compiler.
Possibly it can be improved in future (especially multi-file compilation instead one big bundle).

2021-03-31 12:16 UTC, AlexanderPrendota requested changes

2021-03-31 12:16 UTC, AlexanderPrendota commented on src/main/kotlin/com/compiler/server/compiler/components/KotlinToJSTranslator.kt
> +    useIrCompiler: Boolean
I would suggest using another method called `translateIR()` instead of boolean flag

2021-03-31 12:16 UTC, AlexanderPrendota commented on src/main/kotlin/com/compiler/server/compiler/components/KotlinToJSTranslator.kt
> +    listLines.add(listLines.size - 4, "if (isRewrite) output = new BufferedOutput_0()")
listLines.size - 4
listLines.size - 1

looks like the magic numbers. Please add the comment on why we need such actions. For my point of view it looks like a specific hack

2021-03-31 12:16 UTC, AlexanderPrendota commented on src/main/kotlin/com/compiler/server/compiler/components/KotlinToJSTranslator.kt
> +      createPhaseConfig(jsPhases, K2JsIrCompiler().createArguments(), messageCollector),
Do we need to create K2JsIrCompiler().createArguments() each time when we have a user request?

2021-03-31 12:16 UTC, AlexanderPrendota commented on src/main/kotlin/com/compiler/server/compiler/components/KotlinToJSTranslator.kt
> +      createPhaseConfig(jsPhases, K2JsIrCompiler().createArguments(), messageCollector),
the same questions for other configuration parameters

2021-03-31 12:16 UTC, AlexanderPrendota commented on src/main/kotlin/com/compiler/server/model/Project.kt
> +  fun isJsRelated(): Boolean =
inline 

`=  this == JS || this == JS_IR ||  this == CANVAS`

2021-03-31 12:16 UTC, AlexanderPrendota commented on src/test/kotlin/com/compiler/server/CommandLineArgumentsTest.kt
> +    commandLineArgumentsJsCommon(useIrCompiler = true)
if we want to have the same tests with plain JS compiler we don't need to write additional functions. Let's send the 2 requests per each JS test: 

1) for plain compiler
2) for ir 

and check results one by one

2021-03-31 12:16 UTC, AlexanderPrendota commented on src/main/kotlin/com/compiler/server/compiler/components/KotlinToJSTranslator.kt
> +  private fun doTranslateWithIr(
Do we have differences between IR and PLAIN compilers? We have an "indexes" module to build JSON indexes for auto-imports and competitions

2021-03-31 12:16 UTC, AlexanderPrendota commented on src/test/kotlin/com/compiler/server/CommandLineArgumentsTest.kt
> +    commandLineArgumentsJsCommon(useIrCompiler = true)
also I would suggest using function instead of boolean parameter =)

2021-03-31 13:04 UTC, ilgonmic commented on src/test/kotlin/com/compiler/server/CommandLineArgumentsTest.kt
> +    commandLineArgumentsJsCommon(useIrCompiler = true)
There is test (with `canvas`) which actual only for old compiler for now.
So we can use boolean parameter to distinguish, but it requires copy-paste in "ir" and "old" methods

2021-03-31 13:07 UTC, ilgonmic commented on src/main/kotlin/com/compiler/server/compiler/components/KotlinToJSTranslator.kt
> +  private fun doTranslateWithIr(
It is not actual for stdlib, because stdlib contains both `ir` and `old` compiler, so it can be ok to use `stdlib` to get indices from "old" compiler and use it for IR.

2021-03-31 15:10 UTC, ilgonmic commented on src/main/kotlin/com/compiler/server/model/Project.kt
> +  fun isJsRelated(): Boolean =
Ready

2021-03-31 15:11 UTC, ilgonmic commented on src/main/kotlin/com/compiler/server/compiler/components/KotlinToJSTranslator.kt
> +    useIrCompiler: Boolean
Ready

2021-03-31 15:11 UTC, ilgonmic commented on src/main/kotlin/com/compiler/server/compiler/components/KotlinToJSTranslator.kt
> +    listLines.add(listLines.size - 4, "if (isRewrite) output = new BufferedOutput_0()")
Ready

2021-03-31 15:11 UTC, ilgonmic commented on src/test/kotlin/com/compiler/server/CommandLineArgumentsTest.kt
> +    commandLineArgumentsJsCommon(useIrCompiler = true)
Ready

2021-04-01 06:46 UTC, AlexanderPrendota approved these changes

2021-04-01 06:47 UTC, merged