chore(deps): update deps related to bintray
AlexanderPrendota/kotlin-compiler-server pull request #361
Opened 2021-09-13 11:16 UTC by nikpachoo

I replaced the bintray links with the current ones that I got from the [master branch](https://github.com/AlexanderPrendota/kotlin-compiler-server/blob/master/build.gradle.kts#L56).

2021-09-13 11:23 UTC, AlexanderPrendota commented
@woainikk @anastasiiaSpaseeva Folks, please validate deps

2021-09-13 11:24 UTC, AlexanderPrendota requested changes

2021-09-13 11:24 UTC, AlexanderPrendota commented on build.gradle.kts
> +    implementation("org.jetbrains.kotlin:kotlin-compiler-for-ide:$kotlinVersion-release-310")
I think it;s a bad idea to pass raw string "-release-310" to deps. We always update dependencies via gradle.properties file

2021-09-13 11:24 UTC, AlexanderPrendota commented on common/build.gradle.kts
> +            strictly( "$kotlinVersion-release-310")
why do u need such changes?

2021-09-13 11:34 UTC, woainikk commented on build.gradle.kts
> +    implementation("org.jetbrains.kotlin:kotlin-compiler-for-ide:$kotlinVersion-release-310")
there should be used $kotlinIdeVersion

2021-09-13 11:42 UTC, nikpachoo commented on common/build.gradle.kts
> +            strictly( "$kotlinVersion-release-310")
The problem is that the dependency `org.jetbrains.kotlin:common:202-$kotlinIdeVersion-IJ8194.7` refers to "org.jetbrains.kotlin:kotlin-compiler-for-ide-1.4.30" which cannot be resolved cause there is no such version ([mvnrepository](https://mvnrepository.com/artifact/org.jetbrains.kotlin/kotlin-compiler-for-ide)).

2021-09-13 11:59 UTC, woainikk commented on common/build.gradle.kts
> +            strictly( "$kotlinVersion-release-310")
why kotlin 1.4.30 version used, not the new one (1.5.30)?

2021-09-13 12:04 UTC, AlexanderPrendota commented on build.gradle.kts
> +    implementation("org.jetbrains.kotlin:kotlin-compiler-for-ide:$kotlinVersion-release-310")
riiiiiight

2021-09-13 12:05 UTC, AlexanderPrendota commented
ah exactly, the PR related to kotlin 1.4.30

2021-09-13 12:06 UTC, AlexanderPrendota commented on common/build.gradle.kts
> +            strictly( "$kotlinVersion-release-310")
because the pr into 1430)

2021-09-13 12:20 UTC, nikpachoo commented on build.gradle.kts
> +    implementation("org.jetbrains.kotlin:kotlin-compiler-for-ide:$kotlinVersion-release-310")
I've tried to use $kotlinIdeVersion, but it didn't work. I got an error:
```
Could not find org.jetbrains.kotlin:kotlin-compiler-for-ide:1.4.30-release.
```

2021-09-13 12:32 UTC, AlexanderPrendota requested changes

2021-09-13 12:32 UTC, AlexanderPrendota commented on build.gradle.kts
> +    implementation("org.jetbrains.kotlin:kotlin-compiler-for-ide:$kotlinVersion-release-310")
kotlinVersion=1.4.30-release-310 ?

2021-09-13 15:01 UTC, nikpachoo commented on build.gradle.kts
> +    implementation("org.jetbrains.kotlin:kotlin-compiler-for-ide:$kotlinVersion-release-310")
> kotlinVersion=1.4.30-release-310
nope, because the other dependencies that use this variable stop working.

2021-09-14 07:26 UTC, woainikk approved these changes

2021-09-14 07:43 UTC, merged